apiVersion: batch/v1
kind: Job
metadata:
  name: mci-client-create-job
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mci-client
          image: mci-client:latest
          args: ["create", "example-group"]
          envFrom:
            - configMapRef:
                name: mci-client-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
